import { v4 as uuidv4 } from "uuid";
import type { Template, Scene, CaptionStyle } from "./types";

const defaultCaptionStyle: CaptionStyle = {
  fontFamily: "Inter",
  fontSize: 48,
  fontWeight: 700,
  color: "#ffffff",
  backgroundColor: "rgba(0,0,0,0.6)",
  position: "bottom",
  maxWidth: 80,
  animation: "fade",
};

function makeScene(overrides: Partial<Scene> & { name: string }): Scene {
  return {
    id: uuidv4(),
    durationFrames: 150,
    backgroundColor: "#000000",
    mediaElements: [],
    textElements: [],
    captions: [],
    captionStyle: { ...defaultCaptionStyle },
    transition: "none",
    transitionDurationFrames: 0,
    ...overrides,
  };
}

export const TEMPLATES: Template[] = [
  {
    id: "youtube-standard",
    name: "YouTube Standard",
    description:
      "Classic 16:9 landscape video optimized for YouTube. Includes intro title, main content area, and outro with subscribe CTA.",
    category: "youtube",
    aspectRatio: "16:9",
    thumbnail: "/templates/youtube-standard.png",
    fps: 30,
    captionStyle: { ...defaultCaptionStyle },
    scenes: [
      makeScene({
        name: "Intro",
        durationFrames: 90,
        backgroundColor: "#0f0f1a",
        textElements: [
          {
            id: uuidv4(),
            type: "title",
            text: "Your Video Title",
            position: { x: 50, y: 45 },
            size: { width: 80, height: 20 },
            style: {
              fontFamily: "Inter",
              fontSize: 72,
              fontWeight: 800,
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.1,
              letterSpacing: -1,
              textShadow: "0 4px 20px rgba(0,0,0,0.5)",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 90,
            animation: "fade-in",
          },
          {
            id: uuidv4(),
            type: "subtitle",
            text: "Channel Name",
            position: { x: 50, y: 62 },
            size: { width: 60, height: 8 },
            style: {
              fontFamily: "Inter",
              fontSize: 28,
              fontWeight: 500,
              color: "#94a3b8",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.4,
              letterSpacing: 2,
              textShadow: "none",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 15,
            durationFrames: 75,
            animation: "fade-in",
          },
        ],
        transition: "fade",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "Main Content",
        durationFrames: 300,
        backgroundColor: "#000000",
      }),
      makeScene({
        name: "Outro",
        durationFrames: 150,
        backgroundColor: "#0f0f1a",
        textElements: [
          {
            id: uuidv4(),
            type: "cta",
            text: "Subscribe for more!",
            position: { x: 50, y: 50 },
            size: { width: 60, height: 15 },
            style: {
              fontFamily: "Inter",
              fontSize: 56,
              fontWeight: 700,
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.2,
              letterSpacing: 0,
              textShadow: "0 2px 10px rgba(0,0,0,0.3)",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 150,
            animation: "scale-in",
          },
        ],
        transition: "fade",
        transitionDurationFrames: 15,
      }),
    ],
  },
  {
    id: "youtube-shorts",
    name: "YouTube Shorts",
    description:
      "Vertical 9:16 format perfect for YouTube Shorts, TikTok, and Instagram Reels. Bold text overlays with eye-catching animations.",
    category: "shorts",
    aspectRatio: "9:16",
    thumbnail: "/templates/youtube-shorts.png",
    fps: 30,
    captionStyle: {
      ...defaultCaptionStyle,
      fontSize: 56,
      position: "center",
      animation: "pop",
    },
    scenes: [
      makeScene({
        name: "Hook",
        durationFrames: 60,
        backgroundColor: "#1a0a2e",
        textElements: [
          {
            id: uuidv4(),
            type: "title",
            text: "Wait for it...",
            position: { x: 50, y: 40 },
            size: { width: 85, height: 20 },
            style: {
              fontFamily: "Inter",
              fontSize: 64,
              fontWeight: 800,
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.1,
              letterSpacing: -1,
              textShadow: "0 0 40px rgba(99,102,241,0.5)",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 60,
            animation: "bounce",
          },
        ],
      }),
      makeScene({
        name: "Main Content",
        durationFrames: 360,
        backgroundColor: "#000000",
      }),
      makeScene({
        name: "CTA",
        durationFrames: 90,
        backgroundColor: "#1a0a2e",
        textElements: [
          {
            id: uuidv4(),
            type: "cta",
            text: "Follow for more!",
            position: { x: 50, y: 50 },
            size: { width: 80, height: 15 },
            style: {
              fontFamily: "Inter",
              fontSize: 52,
              fontWeight: 700,
              color: "#ffffff",
              backgroundColor: "rgba(99,102,241,0.3)",
              textAlign: "center",
              lineHeight: 1.3,
              letterSpacing: 0,
              textShadow: "none",
              borderRadius: 16,
              padding: 20,
            },
            startFrame: 0,
            durationFrames: 90,
            animation: "scale-in",
          },
        ],
      }),
    ],
  },
  {
    id: "marketing-promo",
    name: "Marketing Promo",
    description:
      "Professional marketing video template with branded intro, feature highlights, and strong call-to-action. Perfect for product launches and promotions.",
    category: "marketing",
    aspectRatio: "16:9",
    thumbnail: "/templates/marketing-promo.png",
    fps: 30,
    captionStyle: { ...defaultCaptionStyle },
    scenes: [
      makeScene({
        name: "Brand Intro",
        durationFrames: 90,
        backgroundColor: "#0a0a1a",
        textElements: [
          {
            id: uuidv4(),
            type: "title",
            text: "Your Brand",
            position: { x: 50, y: 45 },
            size: { width: 70, height: 20 },
            style: {
              fontFamily: "Inter",
              fontSize: 80,
              fontWeight: 800,
              color: "#6366f1",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.1,
              letterSpacing: -2,
              textShadow: "0 0 60px rgba(99,102,241,0.4)",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 90,
            animation: "scale-in",
          },
          {
            id: uuidv4(),
            type: "subtitle",
            text: "Presents",
            position: { x: 50, y: 60 },
            size: { width: 40, height: 8 },
            style: {
              fontFamily: "Inter",
              fontSize: 24,
              fontWeight: 400,
              color: "#94a3b8",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.4,
              letterSpacing: 6,
              textShadow: "none",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 20,
            durationFrames: 70,
            animation: "fade-in",
          },
        ],
        transition: "fade",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "Feature 1",
        durationFrames: 120,
        backgroundColor: "#0a0a1a",
        textElements: [
          {
            id: uuidv4(),
            type: "lower-third",
            text: "Feature Highlight #1",
            position: { x: 25, y: 80 },
            size: { width: 45, height: 10 },
            style: {
              fontFamily: "Inter",
              fontSize: 32,
              fontWeight: 600,
              color: "#ffffff",
              backgroundColor: "rgba(99,102,241,0.9)",
              textAlign: "left",
              lineHeight: 1.3,
              letterSpacing: 0,
              textShadow: "none",
              borderRadius: 8,
              padding: 16,
            },
            startFrame: 10,
            durationFrames: 100,
            animation: "slide-left",
          },
        ],
        transition: "slide-left",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "Feature 2",
        durationFrames: 120,
        backgroundColor: "#0a0a1a",
        textElements: [
          {
            id: uuidv4(),
            type: "lower-third",
            text: "Feature Highlight #2",
            position: { x: 25, y: 80 },
            size: { width: 45, height: 10 },
            style: {
              fontFamily: "Inter",
              fontSize: 32,
              fontWeight: 600,
              color: "#ffffff",
              backgroundColor: "rgba(99,102,241,0.9)",
              textAlign: "left",
              lineHeight: 1.3,
              letterSpacing: 0,
              textShadow: "none",
              borderRadius: 8,
              padding: 16,
            },
            startFrame: 10,
            durationFrames: 100,
            animation: "slide-left",
          },
        ],
        transition: "slide-left",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "CTA",
        durationFrames: 150,
        backgroundColor: "#0a0a1a",
        textElements: [
          {
            id: uuidv4(),
            type: "cta",
            text: "Get Started Today",
            position: { x: 50, y: 45 },
            size: { width: 70, height: 15 },
            style: {
              fontFamily: "Inter",
              fontSize: 64,
              fontWeight: 800,
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.2,
              letterSpacing: -1,
              textShadow: "0 4px 20px rgba(0,0,0,0.5)",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 150,
            animation: "scale-in",
          },
          {
            id: uuidv4(),
            type: "subtitle",
            text: "yoursite.com",
            position: { x: 50, y: 62 },
            size: { width: 50, height: 8 },
            style: {
              fontFamily: "Inter",
              fontSize: 28,
              fontWeight: 500,
              color: "#6366f1",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.4,
              letterSpacing: 1,
              textShadow: "none",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 20,
            durationFrames: 130,
            animation: "fade-in",
          },
        ],
        transition: "fade",
        transitionDurationFrames: 15,
      }),
    ],
  },
  {
    id: "product-demo",
    name: "Product Demo",
    description:
      "Clean product demonstration template with step-by-step scenes, feature callouts, and professional lower-thirds. Ideal for SaaS demos and tutorials.",
    category: "product",
    aspectRatio: "16:9",
    thumbnail: "/templates/product-demo.png",
    fps: 30,
    captionStyle: {
      ...defaultCaptionStyle,
      fontSize: 36,
      backgroundColor: "rgba(0,0,0,0.8)",
      animation: "highlight-word",
    },
    scenes: [
      makeScene({
        name: "Product Intro",
        durationFrames: 120,
        backgroundColor: "#0f172a",
        textElements: [
          {
            id: uuidv4(),
            type: "title",
            text: "Product Name",
            position: { x: 50, y: 40 },
            size: { width: 70, height: 18 },
            style: {
              fontFamily: "Inter",
              fontSize: 72,
              fontWeight: 800,
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.1,
              letterSpacing: -1,
              textShadow: "none",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 120,
            animation: "fade-in",
          },
          {
            id: uuidv4(),
            type: "subtitle",
            text: "The better way to get things done",
            position: { x: 50, y: 58 },
            size: { width: 60, height: 10 },
            style: {
              fontFamily: "Inter",
              fontSize: 28,
              fontWeight: 400,
              color: "#94a3b8",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.4,
              letterSpacing: 0,
              textShadow: "none",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 15,
            durationFrames: 105,
            animation: "fade-in",
          },
        ],
        transition: "fade",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "Step 1",
        durationFrames: 180,
        backgroundColor: "#0f172a",
        textElements: [
          {
            id: uuidv4(),
            type: "lower-third",
            text: "Step 1: Getting Started",
            position: { x: 25, y: 85 },
            size: { width: 45, height: 8 },
            style: {
              fontFamily: "Inter",
              fontSize: 28,
              fontWeight: 600,
              color: "#ffffff",
              backgroundColor: "rgba(15,23,42,0.9)",
              textAlign: "left",
              lineHeight: 1.3,
              letterSpacing: 0,
              textShadow: "none",
              borderRadius: 8,
              padding: 14,
            },
            startFrame: 10,
            durationFrames: 160,
            animation: "slide-up",
          },
        ],
        transition: "slide-left",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "Step 2",
        durationFrames: 180,
        backgroundColor: "#0f172a",
        textElements: [
          {
            id: uuidv4(),
            type: "lower-third",
            text: "Step 2: Core Features",
            position: { x: 25, y: 85 },
            size: { width: 45, height: 8 },
            style: {
              fontFamily: "Inter",
              fontSize: 28,
              fontWeight: 600,
              color: "#ffffff",
              backgroundColor: "rgba(15,23,42,0.9)",
              textAlign: "left",
              lineHeight: 1.3,
              letterSpacing: 0,
              textShadow: "none",
              borderRadius: 8,
              padding: 14,
            },
            startFrame: 10,
            durationFrames: 160,
            animation: "slide-up",
          },
        ],
        transition: "slide-left",
        transitionDurationFrames: 15,
      }),
      makeScene({
        name: "Wrap Up",
        durationFrames: 120,
        backgroundColor: "#0f172a",
        textElements: [
          {
            id: uuidv4(),
            type: "cta",
            text: "Try it free today",
            position: { x: 50, y: 50 },
            size: { width: 60, height: 12 },
            style: {
              fontFamily: "Inter",
              fontSize: 56,
              fontWeight: 700,
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              lineHeight: 1.2,
              letterSpacing: -1,
              textShadow: "0 4px 20px rgba(0,0,0,0.3)",
              borderRadius: 0,
              padding: 0,
            },
            startFrame: 0,
            durationFrames: 120,
            animation: "scale-in",
          },
        ],
        transition: "fade",
        transitionDurationFrames: 15,
      }),
    ],
  },
];
